name: Build & Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: main-cicd
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build with ncc
      run: |
        npm install -g yarn
        yarn install
        yarn run build

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9.1.0
      with:
        message: "rebuild"
